review:
  prompt: >
    Please review the code thoroughly with a focus on code quality, readability, structure, performance, and error handling.
    Provide your feedback in Korean, and suggest possible improvements where applicable.
  files: "**/*.{ts,tsx,js,jsx}"
  exclude: "**/*.test.{ts,tsx}"
