review:
  prompt: >
    Please review the code focusing on quality, readability, structure, performance, and error handling.
    Only provide concise feedback in Korean. 
    Do not include walkthroughs, summaries, or sequence diagrams. 
    Just suggest clear and actionable improvements.
