language: ko
review:
  prompt: >
    한국어로 코드의 품질, 가독성, 구조, 성능, 에러 처리 중심으로 리뷰해주세요.
    코드 흐름 설명, 요약, 시퀀스 다이어그램은 포함하지 마세요.
    PR 설명은 수정하지 마세요.
    개선이 필요한 부분에 대해 구체적이고 실행 가능한 제안을 해주세요.
  files: "**/*.{ts,tsx,js,jsx}"
  exclude: "**/*.test.{ts,tsx}"
