export const PATH_IMAGES = {
  POPULAR: "/images/popular.png",
  RECENT: "/images/recent.png",
  DRAMA: "/images/drama.png",
  MOVIE: "/images/movie.png",

  CUSTOM_BG: "/images/custom-bg.png",
  EVENT_BANNER: "/images/event-banner.png",

  FAVICON: "/images/favicon.png",

  //임시 이미지
  IMAGE: "/images/image.png",
  TMP_MAP: "/images/tmp-map.png",
  TMP_MOVIE: "/images/tmp-movie.png",

  TRAIT: {
    MOVIE_DETAIL_COLLECTOR: "/images/trait/movie1.png",
    MOVIE_SHARED_EMOTER: "/images/trait/movie2.png",
    DRAMA_STORY_IMMERSER: "/images/trait/movie3.png",
    DRAMA_SOCIAL_FAN: "/images/trait/movie4.png",
    VARIETY_DETAIL_ANALYST: "/images/trait/movie5.png",
    VARIETY_REACTION_SHARER: "/images/trait/movie6.png",
    SPORTS_FULL_SUPPORTER: "/images/trait/movie7.png",
    SPORTS_MOMENT_LOVER: "/images/trait/movie8.png",
    CONCERT_STAGE_DIVER: "/images/trait/movie9.png",
    CONCERT_FANCAM_LOVER: "/images/trait/movie10.png",
    BACKGROUND: "/images/trait/gradation-background.png",
  },
};

export const MOCK_IMAGES = {
  IMAGE_1: "/mock_images/mock-image-1.png",
  IMAGE_2: "/mock_images/mock-image-2.png",
  IMAGE_3: "/mock_images/mock-image-3.png",
  IMAGE_4: "/mock_images/mock-image-4.png",
  IMAGE_5: "/mock_images/mock-image-5.png",
  IMAGE_6: "/mock_images/mock-image-6.png",
  IMAGE_7: "/mock_images/mock-image-7.png",
  IMAGE_8: "/mock_images/mock-image-8.png",
  IMAGE_9: "/mock_images/mock-image-9.png",
  IMAGE_10: "/mock_images/mock-image-10.png",
  IMAGE_11: "/mock_images/mock-image-11.png",
  IMAGE_12: "/mock_images/mock-image-12.png",
  IMAGE_13: "/mock_images/mock-image-13.png",
  IMAGE_14: "/mock_images/mock-image-14.png",
  IMAGE_15: "/mock_images/mock-image-15.png",
  IMAGE_16: "/mock_images/mock-image-16.png",
  IMAGE_17: "/mock_images/mock-image-17.png",
  IMAGE_18: "/mock_images/mock-image-18.png",
  IMAGE_19: "/mock_images/mock-image-19.png",
  IMAGE_20: "/mock_images/mock-image-20.png",
  IMAGE_21: "/mock_images/mock-image-21.png",
  IMAGE_22: "/mock_images/mock-image-22.png",
  IMAGE_23: "/mock_images/mock-image-23.png",
  IMAGE_24: "/mock_images/mock-image-24.png",
  IMAGE_25: "/mock_images/mock-image-25.png",
  IMAGE_CINEMA_1: "/mock_images/place-1.png",
  IMAGE_CINEMA_2: "/mock_images/place-2.png",
  IMAGE_CINEMA_3: "/mock_images/place-3.png",
  IMAGE_CINEMA_4: "/mock_images/place-4.png",
};
