name: 🎨 Design
description: 마크업 및 스타일 관련 작업이 필요할 때 사용하세요.
title: "[🎨 Design] "
labels: ["🎨 Design"]
body:
  - type: textarea
    id: goal
    attributes:
      label: 🎯 목표
      description: 작업하고자 하는 마크업 또는 스타일 요소를 설명해 주세요.
      placeholder: |
        예: 모바일 화면에서 카드 UI 정렬 수정
    validations:
      required: true

  - type: textarea
    id: design-reference
    attributes:
      label: 💡 참고 디자인 / 요구사항
      description: 참고할 디자인 시안이나 구체적인 요구사항을 작성해 주세요.
      placeholder: |
        예: Figma 링크 또는 기획 문서

  - type: textarea
    id: remarks
    attributes:
      label: 📒 Remarks
      description: 추가로 전달할 메모가 있다면 자유롭게 작성해 주세요.
      placeholder: |
        예: 해당 디자인 시안은 이전 이슈에서도 사용되었음
