export const mockCinemas = [
  {
    id: 1,
    name: "코엑스",
    hall: "더 부티크 프라이빗 1관",
    tags: ["소규모", "프리미엄", "연인", "가족"],
    address: "서울 마포구 상암동 1602 DMC 단지",
    seats: "321석(장애인석 구비)",
    price: "시간당 2만원",
    image: "/mock_imges/place-2.png",
  },
  {
    id: 2,
    name: "한국영상자료원",
    hall: "시네마테크KOFA 1관",
    tags: ["대규모", "단체", "현장감", "웅장감"],
    address: "서울 마포구 상암동 1602 DMC 단지",
    seats: "321석(장애인석 구비)",
    price: "시간당 4만원",
    image: "/mock_imges/place-1.png",
  },
  {
    id: 3,
    name: "코엑스",
    hall: "더 부티크 프라이빗 2관",
    tags: ["소규모", "프리미엄", "연인", "가족"],
    address: "서울 마포구 상암동 1602 DMC 단지",
    seats: "321석(장애인석 구비)",
    price: "시간당 2만원",
    image: "/mock_imges/place-3.png",
  },
  {
    id: 4,
    name: "코엑스",
    hall: "더 부티크 프라이빗 1관",
    tags: ["소규모", "프리미엄", "연인", "가족"],
    address: "서울 마포구 상암동 1602 DMC 단지",
    seats: "321석(장애인석 구비)",
    price: "시간당 2만원",
    image: "/mock_imges/place-2.png",
  },
];
