export const MOVIE_LISTS = [
  {
    imageUrl: "/image.png",
    category: "영화",
    title: "블레이드 러너",
    placeAndDate: "CGV 강남 | 2025.05.12",
    description:
      "디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계",
    ddayBadge: "D-3",
    statusBadge: "예매 가능",
    progressRate: "75%",
    estimatedPrice: "13,000원",
  },
  {
    imageUrl: "/image.png",
    category: "영화",
    title: "인터스텔라",
    placeAndDate: "메가박스 코엑스 | 2025.05.10",
    description: "시간과 공간을 넘는 감동적인 여정",
    ddayBadge: "D-1",
    statusBadge: "예매 마감",
    progressRate: "90%",
    estimatedPrice: "14,000원",
  },
  {
    imageUrl: "/image.png",
    category: "코미디",
    title: "극한직업",
    placeAndDate: "롯데시네마 홍대 | 2025.05.15",
    description: "치킨집 위장수사 코미디",
    ddayBadge: "D-6",
    statusBadge: "예매 가능",
    progressRate: "60%",
    estimatedPrice: "12,000원",
  },
  {
    imageUrl: "/image.png",
    category: "드라마",
    title: "기생충",
    placeAndDate: "CGV 용산 | 2025.05.14",
    description: "계급 간 충돌을 그린 블랙 코미디",
    ddayBadge: "D-5",
    statusBadge: "예매 가능",
    progressRate: "80%",
    estimatedPrice: "13,500원",
  },
  {
    imageUrl: "/image.png",
    category: "애니메이션",
    title: "센과 치히로의 행방불명",
    placeAndDate: "메가박스 센텀시티 | 2025.05.20",
    description: "신비한 세계에서 성장하는 치히로의 모험",
    ddayBadge: "D-11",
    statusBadge: "예매 대기",
    progressRate: "45%",
    estimatedPrice: "10,000원",
  },
  {
    imageUrl: "/image.png",
    category: "로맨스",
    title: "어바웃 타임",
    placeAndDate: "롯데시네마 건대 | 2025.05.11",
    description: "시간여행과 사랑이 어우러진 이야기",
    ddayBadge: "D-2",
    statusBadge: "예매 가능",
    progressRate: "70%",
    estimatedPrice: "11,000원",
  },
  {
    imageUrl: "/image.png",
    category: "스릴러",
    title: "유전",
    placeAndDate: "CGV 수원 | 2025.05.18",
    description: "가족의 비밀이 밝혀지는 공포 스릴러",
    ddayBadge: "D-9",
    statusBadge: "예매 가능",
    progressRate: "65%",
    estimatedPrice: "13,000원",
  },
  {
    imageUrl: "/image.png",
    category: "판타지",
    title: "반지의 제왕",
    placeAndDate: "메가박스 왕십리 | 2025.05.22",
    description: "중간계의 운명을 건 위대한 여정",
    ddayBadge: "D-13",
    statusBadge: "예매 대기",
    progressRate: "50%",
    estimatedPrice: "15,000원",
  },
  {
    imageUrl: "/image.png",
    category: "공포",
    title: "겟 아웃",
    placeAndDate: "CGV 신촌 | 2025.05.09",
    description: "인종과 공포가 교차하는 서스펜스",
    ddayBadge: "D-DAY",
    statusBadge: "상영 중",
    progressRate: "100%",
    estimatedPrice: "13,000원",
  },
  {
    imageUrl: "/image.png",
    category: "범죄",
    title: "조커",
    placeAndDate: "롯데시네마 부산본점 | 2025.05.13",
    description: "광기의 탄생, 조커의 이야기",
    ddayBadge: "D-4",
    statusBadge: "예매 가능",
    progressRate: "85%",
    estimatedPrice: "14,500원",
  },
  {
    imageUrl: "/image.png",
    category: "영화",
    title: "블레이드 러너",
    placeAndDate: "CGV 강남 | 2025.05.12",
    description:
      "디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계",
    ddayBadge: "D-3",
    statusBadge: "예매 가능",
    progressRate: "75%",
    estimatedPrice: "13,000원",
  },
  {
    imageUrl: "/image.png",
    category: "영화",
    title: "블레이드 러너",
    placeAndDate: "CGV 강남 | 2025.05.12",
    description:
      "디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계",
    ddayBadge: "D-3",
    statusBadge: "예매 가능",
    progressRate: "75%",
    estimatedPrice: "13,000원",
  },
  {
    imageUrl: "/image.png",
    category: "영화",
    title: "블레이드 러너",
    placeAndDate: "CGV 강남 | 2025.05.12",
    description:
      "디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계",
    ddayBadge: "D-3",
    statusBadge: "예매 가능",
    progressRate: "75%",
    estimatedPrice: "13,000원",
  },
  {
    imageUrl: "/image.png",
    category: "영화",
    title: "블레이드 러너",
    placeAndDate: "CGV 강남 | 2025.05.12",
    description:
      "디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계",
    ddayBadge: "D-3",
    statusBadge: "예매 가능",
    progressRate: "75%",
    estimatedPrice: "13,000원",
  },
  {
    imageUrl: "/image.png",
    category: "영화",
    title: "블레이드 러너",
    placeAndDate: "CGV 강남 | 2025.05.12",
    description:
      "디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계",
    ddayBadge: "D-3",
    statusBadge: "예매 가능",
    progressRate: "75%",
    estimatedPrice: "13,000원",
  },
  {
    imageUrl: "/image.png",
    category: "영화",
    title: "블레이드 러너",
    placeAndDate: "CGV 강남 | 2025.05.12",
    description:
      "디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계",
    ddayBadge: "D-3",
    statusBadge: "예매 가능",
    progressRate: "75%",
    estimatedPrice: "13,000원",
  },
  {
    imageUrl: "/image.png",
    category: "영화",
    title: "블레이드 러너",
    placeAndDate: "CGV 강남 | 2025.05.12",
    description:
      "디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계",
    ddayBadge: "D-3",
    statusBadge: "예매 가능",
    progressRate: "75%",
    estimatedPrice: "13,000원",
  },
  {
    imageUrl: "/image.png",
    category: "영화",
    title: "블레이드 러너",
    placeAndDate: "CGV 강남 | 2025.05.12",
    description:
      "디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계",
    ddayBadge: "D-3",
    statusBadge: "예매 가능",
    progressRate: "75%",
    estimatedPrice: "13,000원",
  },
  {
    imageUrl: "/image.png",
    category: "영화",
    title: "블레이드 러너",
    placeAndDate: "CGV 강남 | 2025.05.12",
    description:
      "디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계디스토피아 속 인간과 복제인의 경계",
    ddayBadge: "D-3",
    statusBadge: "예매 가능",
    progressRate: "75%",
    estimatedPrice: "13,000원",
  },
];
