name: "Auto Assign"

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign reviewers and assignees
        uses: kentaro-m/auto-assign@v1.2.3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          addReviewers: true
          addAssignees: author
          reviewers: |
            anhyeryeon2
            Sohyunnnn
          numberOfReviewers: 0
          numberOfAssignees: 2
          skipKeywords: |
            wip
